blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community Forum
    url: https://community.home-assistant.io/
    about: For general Home Assistant questions and setup help.
  - name: HACS documentation
    url: https://hacs.xyz/
    about: Documentation for the Home Assistant Community Store.
